modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-v3"

[[mods]]
modId="thereisnothingtobeafraidofanymore"
version="${file.jarVersion}"
displayName="ThereIsNothingToBeAfraidOfAnymore"
authors="TeamPotato"
description='''
A Minecraft mod.
'''